### PR TITLE
move mod_loader into an addon folder

### PR DESCRIPTION
**Pull request by Qubus0**

### CODE REVIEW

**Review by ithinkandicode — APPROVED** [review]
Approved! 👍

**Review by otDan — COMMENTED** [review]
Is there a reason to call the folder mod_loader_tools instead of just mod_loader?

**Comment by Qubus0** [comment]
@otDan 
> with the other things in there and a modularity with the interface for example it made more sense to call it a toolset, for me at least
and I feel like we'll be expanding on this thing as well

**Comment by ithinkandicode** [comment]
I do think *mod_loader* is cleaner. "Mod Loader Tools" suggests that it's a set of tools for the mod loader, rather than the mod loader itself

**Comment by otDan** [comment]
> I do think _mod_loader_ is cleaner. "Mod Loader Tools" suggests that it's a set of tools for the mod loader, rather than the mod loader itself

I agree with this

**Comment by KANAjetzt** [comment]
What do we do with ``run.gd``? 
Its a bit out of place.

Should be add a *"game_dir_copy"* folder? 
Until we can get rid of ``run.gd``.

**Review by ithinkandicode — APPROVED** [review]
Approved

**Review by KANAjetzt — APPROVED** [review]
lets go 🔥

**Comment by Qubus0** [comment]
run.gd won't be around for long. new flag is `--script addons/mod_loader/run.gd`

**Pull request merged**
