### PR TITLE
Fix mod id validation

### PR DESCRIPTION
**Pull request by Qubus0**
really simple check for length 3
@ithinkandicode do we really need all of that `type` stuff at the beginning of the method? what was the intended use for that and will that be followed up upon?

### CODE REVIEW

**Comment by KANAjetzt** [comment]
What type stuff exactly? 
That one?

https://github.com/GodotModding/godot-mod-loader/blob/bc09c110c4bde727886e31a5cbbf2b9b852294a1/addons/mod_loader/classes/mod_manifest.gd#L354

**Comment by KANAjetzt** [comment]
It's used in the error message to pass the field name.

https://github.com/GodotModding/godot-mod-loader/blob/bc09c110c4bde727886e31a5cbbf2b9b852294a1/addons/mod_loader/classes/mod_manifest.gd#L101-L104

**Comment by Qubus0** [comment]
oh I missed the usage in that. disregard that comment then

**Review by KANAjetzt — APPROVED** [review]
Approved ✅ 
Do we consider this a breaking change? 😬

**Pull request merged**
