### PR TITLE
4.x branch update to 6.0.2 version

### PR DESCRIPTION
**Pull request by MateuSai**
I checked the merge changes of versions 6.0.1 and 6.0.2 and I made the necessary changes to the 4.x branch

### CODE REVIEW

**Comment by MateuSai** [comment]
Let me explain what I did on the last commit. I was getting this error:

"FATAL-ERROR ModLoader:File: Encountered an error when attempting to open a file, with the path: user://mod_user_profiles.json"

So, I checked the `_save_string_to_file` function and I found this:

```swift
static func _save_string_to_file(save_string: String, filepath: String) -> bool:
	# Create directory if it doesn't exist yet
	var file_directory := filepath.get_base_dir()
	var dir := DirAccess.open(file_directory)

	_code_note(str(
		"View error codes here:",
		"https://docs.godotengine.org/en/stable/classes/class_%40globalscope.html#enum-globalscope-error"
	))

	if not dir.dir_exists(file_directory):
		var makedir_error := dir.make_dir_recursive(file_directory)
		if not makedir_error == OK:
			ModLoaderLog.fatal("Encountered an error (%s) when attempting to create a directory, with the path: %s" % [makedir_error, file_directory], LOG_NAME)
			return false

	if file_exists(filepath):
		ModLoaderLog.fatal("Encountered an error when attempting to open a file, with the path: %s" % [filepath], LOG_NAME)
		return false

	# Save data to the file
	var file := FileAccess.open(filepath, FileAccess.WRITE)

	file.store_string(save_string)
	file.close()

	return true
```

It's throwing an error if the file already exists, which I think is wrong since user://mod_user_profiles.json should be overwritten. I checked the same function on the main branch and it's like this:

```swift
static func _save_string_to_file(save_string: String, filepath: String) -> bool:
	# Create directory if it doesn't exist yet
	var file_directory := filepath.get_base_dir()
	var dir := Directory.new()

	_code_note(str(
		"View error codes here:",
		"https://docs.godotengine.org/en/stable/classes/class_%40globalscope.html#enum-globalscope-error"
	))

	if not dir.dir_exists(file_directory):
		var makedir_error := dir.make_dir_recursive(file_directory)
		if not makedir_error == OK:
			ModLoaderLog.fatal("Encountered an error (%s) when attempting to create a directory, with the path: %s" % [makedir_error, file_directory], LOG_NAME)
			return false

	var file := File.new()

	# Save data to the file
	var fileopen_error := file.open(filepath, File.WRITE)

	if not fileopen_error == OK:
		ModLoaderLog.fatal("Encountered an error (%s) when attempting to write to a file, with the path: %s" % [fileopen_error, filepath], LOG_NAME)
		return false

	file.store_string(save_string)
	file.close()

	return true

```

As you see, here it throws an error if it can't open the file, not if the file already exists. So I modified the code on the 4.x branch so that it does the same:

```swift
static func _save_string_to_file(save_string: String, filepath: String) -> bool:
	# Create directory if it doesn't exist yet
	var file_directory := filepath.get_base_dir()
	var dir := DirAccess.open(file_directory)

	_code_note(str(
		"View error codes here:",
		"https://docs.godotengine.org/en/stable/classes/class_%40globalscope.html#enum-globalscope-error"
	))

	if not dir.dir_exists(file_directory):
		var makedir_error := dir.make_dir_recursive(file_directory)
		if not makedir_error == OK:
			ModLoaderLog.fatal("Encountered an error (%s) when attempting to create a directory, with the path: %s" % [makedir_error, file_directory], LOG_NAME)
			return false

	# Save data to the file
	var file := FileAccess.open(filepath, FileAccess.WRITE)

	if not file:
		ModLoaderLog.fatal("Encountered an error when attempting to open a file, with the path: %s" % [filepath], LOG_NAME)
		return false

	file.store_string(save_string)
	file.close()

	return true
```

**Comment by otDan** [comment]
I was holding off from porting latest since no one tested 4.x in general

**Comment by KANAjetzt** [comment]
@MateuSai is testing it now, what do you think is the best way to update the 4.x branch to 6.2.0 @otDan ?
Looks like the first issue hit, are the bugs we fixed in the later versions.

**Review by KANAjetzt — APPROVED** [review]
Nice work - Thank You! 🥇

**Pull request merged**
