### PR TITLE
Split off logging and utils

### LINKED ISSUE #21: Different log levels for mod_log
> Ste — Today at 16:23
> should we have different logs levels for mod_log? INFO, WARNING, ERROR and just add those at the front of the line? would make reading the logs easier if you use a highlighter

Something like:

`11.1.2023 - 08:28:20   ModLoader-INFO: Initializing -> Cube-HarvestCalc`

### PR DESCRIPTION
**Pull request by Qubus0**
This needs to be merged after 
- #60 

Breaking changes:
Removed:
```
ModLoader.
mod_log
dev_log
```

Use the following instead:
```
ModLoaderUtils.
log_fatal()
log_error()
log_warning()
log_info()
log_success()
log_debug()
log_debug_json_print()
```
closes #21

### CODE REVIEW

**Comment by otDan** [comment]
probably switching back to the single method and just adding an enum to specify the log type is better

**Comment by Qubus0** [comment]
Any particular reason for that? That would mean having to reference the enum every single time for logging, e.g.
```gdscript
ModLoaderUtils.mod_log("some message here: %s" % some_value, ModLoaderUtils.verbosity_level.INFO, LOG_NAME)
# and this if you also want the json print included in the same method
ModLoaderUtils.mod_log("some message here: %s" % some_value, ModLoaderUtils.verbosity_level.INFO, LOG_NAME, true)
```
compared to this.
```gdscript
ModLoaderUtils.log_info("some message here: %s" % some_value, LOG_NAME)
```
I feel like it's much more concise and better to understand at a glance

**Review by otDan — APPROVED** [review]
well other than that comment, everything seems to be in place and working

**Review by ithinkandicode — APPROVED** [review]
Lookin' good man!

**Pull request merged**
